services:
  quiethn:
    image: unit:php8.4
    container_name: quiethn
    volumes:
      - /etc/localtime:/etc/localtime:ro # Use timezone from host
      - ./nginx-unit-config:/docker-entrypoint.d
      - ./src:/www
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: pangolin
